// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtSnbAgLmhjxj2mWXoRXyS3T1AO3z7hYQ',
    appId: '1:583247195358:web:e68f9d308939a78378264f',
    messagingSenderId: '583247195358',
    projectId: 'bibliotheque-app-ea54a',
    authDomain: 'bibliotheque-app-ea54a.firebaseapp.com',
    storageBucket: 'bibliotheque-app-ea54a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKrUNMKxhP6WFLgo4Pnp6Z53KjtZVoQ-4',
    appId: '1:583247195358:android:0f82777ec496d9a578264f',
    messagingSenderId: '583247195358',
    projectId: 'bibliotheque-app-ea54a',
    storageBucket: 'bibliotheque-app-ea54a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh65ghHu8UaLypK3NjsM4-uoxLFHn45h4',
    appId: '1:583247195358:ios:4985b95583a71b8878264f',
    messagingSenderId: '583247195358',
    projectId: 'bibliotheque-app-ea54a',
    storageBucket: 'bibliotheque-app-ea54a.firebasestorage.app',
    iosBundleId: 'com.example.bibliothequeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh65ghHu8UaLypK3NjsM4-uoxLFHn45h4',
    appId: '1:583247195358:ios:4985b95583a71b8878264f',
    messagingSenderId: '583247195358',
    projectId: 'bibliotheque-app-ea54a',
    storageBucket: 'bibliotheque-app-ea54a.firebasestorage.app',
    iosBundleId: 'com.example.bibliothequeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtSnbAgLmhjxj2mWXoRXyS3T1AO3z7hYQ',
    appId: '1:583247195358:web:11334cdb2bf277f178264f',
    messagingSenderId: '583247195358',
    projectId: 'bibliotheque-app-ea54a',
    authDomain: 'bibliotheque-app-ea54a.firebaseapp.com',
    storageBucket: 'bibliotheque-app-ea54a.firebasestorage.app',
  );
}
